# Generated by Django 4.2.7 on 2026-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.IntegerField(db_column='AccountID', primary_key=True, serialize=False)),
                ('accountname', models.CharField(blank=True, db_column='AccountName', max_length=50, null=True)),
                ('accountnumber', models.CharField(blank=True, db_column='AccountNumber', max_length=50, null=True)),
            ],
            options={
                'db_table': '[stg].[Accounts]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allmarriages',
            fields=[
                ('marriage_id', models.IntegerField(db_column='Marriage_ID', primary_key=True, serialize=False)),
                ('groomfirstname', models.CharField(blank=True, db_column='GroomFirstName', max_length=50, null=True)),
                ('groomlastname', models.CharField(blank=True, db_column='GroomLastName', max_length=50, null=True)),
                ('bridefirstname', models.CharField(blank=True, db_column='BrideFirstName', max_length=50, null=True)),
                ('bridelastname', models.CharField(blank=True, db_column='BrideLastName', max_length=50, null=True)),
                ('dateofmarriage', models.DateTimeField(blank=True, db_column='DateofMarriage', null=True)),
                ('town_marriage', models.CharField(blank=True, db_column='Town_marriage', max_length=25, null=True)),
            ],
            options={
                'db_table': 'AllMarriages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Civilunion',
            fields=[
                ('union_id', models.IntegerField(db_column='Union_ID', primary_key=True, serialize=False)),
                ('party1_firstname', models.CharField(blank=True, db_column='Party1_FirstName', max_length=50, null=True)),
                ('party1lastname', models.CharField(blank=True, db_column='Party1LastName', max_length=50, null=True)),
                ('party2firstname', models.CharField(blank=True, db_column='Party2FirstName', max_length=50, null=True)),
                ('party2lastname', models.CharField(blank=True, db_column='Party2LastName', max_length=50, null=True)),
                ('dateofunion', models.DateTimeField(blank=True, db_column='DateofUnion', null=True)),
            ],
            options={
                'db_table': 'CivilUnion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('entry_date', models.CharField(blank=True, db_column='Entry_Date', max_length=255, null=True)),
                ('date_of_death', models.CharField(blank=True, db_column='Date Of Death', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Lastname', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, db_column='First Name', max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, db_column='Street Address', max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, db_column='Date Of Birth', max_length=255, null=True)),
                ('page_number', models.CharField(blank=True, db_column='Page Number', max_length=255, null=True)),
                ('non_eh', models.CharField(blank=True, db_column='Non_EH', max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=255, null=True)),
                ('town', models.CharField(blank=True, db_column='Town', max_length=255, null=True)),
            ],
            options={
                'db_table': '[stg].[Deaths]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marriagelicense',
            fields=[
                ('marriage_id', models.CharField(db_column='Marriage_ID', max_length=255, primary_key=True, serialize=False)),
                ('groomfirstname', models.CharField(blank=True, db_column='GroomFirstName', max_length=255, null=True)),
                ('groommiddlename', models.CharField(blank=True, db_column='GroomMiddleName', max_length=255, null=True)),
                ('groomlastname', models.CharField(blank=True, db_column='GroomLastName', max_length=255, null=True)),
                ('bridefirstname', models.CharField(blank=True, db_column='BrideFirstName', max_length=255, null=True)),
                ('bridemiddlename', models.CharField(blank=True, db_column='BrideMiddleName', max_length=255, null=True)),
                ('bridelastname', models.CharField(blank=True, db_column='BrideLastName', max_length=255, null=True)),
                ('town_marriage', models.CharField(blank=True, db_column='Town_marriage', max_length=255, null=True)),
                ('date_issued', models.CharField(blank=True, db_column='Date_Issued', max_length=255, null=True)),
                ('dateofmarriage', models.CharField(blank=True, db_column='DateofMarriage', max_length=255, null=True)),
            ],
            options={
                'db_table': '[stg].[MarriageLicense]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marriagesfrombooks',
            fields=[
                ('bookmar_id', models.IntegerField(db_column='BookMar_ID', primary_key=True, serialize=False)),
                ('groom_lastname', models.CharField(blank=True, db_column='Groom _LastName', max_length=50, null=True)),
                ('groom_firsttname', models.CharField(blank=True, db_column='Groom _FirsttName', max_length=50, null=True)),
                ('bride_lastname', models.CharField(blank=True, db_column='Bride_LastName', max_length=50, null=True)),
                ('bride_firstname', models.CharField(blank=True, db_column='Bride_FirstName', max_length=50, null=True)),
                ('date_of_marriage', models.DateTimeField(blank=True, db_column='Date_Of_ Marriage', null=True)),
            ],
            options={
                'db_table': 'MarriagesfromBooks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refbranch',
            fields=[
                ('branchid', models.CharField(db_column='BranchID', max_length=255, primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=255, null=True)),
            ],
            options={
                'db_table': '[stg].[refBranch]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(db_column='Transaction_ID', max_length=255, primary_key=True, serialize=False)),
                ('transactionnumber', models.CharField(blank=True, db_column='TransactionNumber', max_length=255, null=True)),
                ('transactiondate', models.CharField(blank=True, db_column='TransactionDate', max_length=255, null=True)),
                ('entered_by', models.CharField(blank=True, db_column='Entered BY', max_length=255, null=True)),
                ('accountid', models.CharField(blank=True, db_column='AccountID', max_length=255, null=True)),
                ('depositamount', models.CharField(blank=True, db_column='DepositAmount', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
            ],
            options={
                'db_table': '[stg].[Transactions]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vet_id', models.CharField(db_column='Vet_ID', max_length=255, primary_key=True, serialize=False)),
                ('lname', models.CharField(blank=True, db_column='Lname', max_length=255, null=True)),
                ('fname', models.CharField(blank=True, db_column='FName', max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True)),
                ('stnum', models.CharField(blank=True, db_column='StNum', max_length=255, null=True)),
                ('town', models.CharField(blank=True, db_column='Town', max_length=255, null=True)),
                ('st', models.CharField(blank=True, db_column='ST', max_length=255, null=True)),
                ('streetname', models.CharField(blank=True, db_column='StreetName', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, db_column='Unit', max_length=255, null=True)),
                ('volume', models.CharField(blank=True, db_column='Volume', max_length=255, null=True)),
                ('page', models.CharField(blank=True, db_column='Page', max_length=255, null=True)),
                ('enlistment_date', models.CharField(blank=True, db_column='Enlistment_Date', max_length=255, null=True)),
                ('discharge_date', models.CharField(blank=True, db_column='Discharge_Date', max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, db_column='Birth_Date', max_length=255, null=True)),
                ('recording_date', models.CharField(blank=True, db_column='Recording_Date', max_length=255, null=True)),
                ('branch', models.CharField(blank=True, db_column='Branch', max_length=255, null=True)),
                ('spousepartner', models.CharField(blank=True, db_column='SpousePartner', max_length=255, null=True)),
            ],
            options={
                'db_table': '[stg].[vet]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmitelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
