# Generated by Django 4.2.7 on 2026-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerks', '0002_accounts_allmarriages_civilunion_deaths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmittalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('prepared_by', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('line_items', models.JSONField(default=list)),
                ('grand_total_checks', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
